### ISSUE TITLE
"Sorry, you've reached the limit of messages you can send to Copilot within the hour. Check back soon!"

### ISSUE THREAD

**Issue by simonelmundo** [qzxtu/Copilot-Chat-Pro#4]
I sent it my code which was 750 lines long, when I pressed sent, it kept looping between "trying to reconnect" and "stop responding " button . After a minute or so , it gave me "Sorry, you've reached the limit of messages you can send to Copilot within the hour. Check back soon!" And then I couldn't send anymore messages even very short ones.

 Also HUUGE thank you for this extension

**Comment by fl2on** [comment]
Hi, sorry for the delay in replying. In general, the extension is still working, but the actual limit set by the Copilot backend code is about 23,870 characters in total. It is likely that this limit has been exceeded and caused the problem. In addition, Copilot may have made other changes, further reducing the total character limit due to recent updates. Recently, I tested it with a 553 line code, and there was no problem. However, if the code exceeds that amount, it is likely that the backend limit in Copilot will cause a message indicating that the response is imcomplete. Once the daily limit is reset, you should be able to use Copilot normally again.


![image](https://github.com/qzxtu/Copilot-Chat-Pro/assets/69091361/ea5c97fd-11b7-4eac-80ff-7a9d1ef21b64)
![image](https://github.com/qzxtu/Copilot-Chat-Pro/assets/69091361/1136377e-55b2-494d-a35e-f19db5bb740f)
